# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Upload to PyPI

on:
  workflow_dispatch:
    inputs:
      pypi-target:
        description: 'PyPI Target'
        required: true
        default: 'test'
        type: choice
        options:
          - 'test'
          - 'prod'

  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  determine-target:
    name: Determine PyPI Target
    runs-on: ubuntu-latest
    outputs:
      pypi-target: ${{ steps.set-target.outputs.pypi-target }}
    
    steps:
      - name: Set PyPI target
        id: set-target
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TARGET="${{ github.event.inputs.pypi-target }}"
          else
            TARGET="test"
          fi
          echo "pypi-target=$TARGET" >> $GITHUB_OUTPUT
          echo "::notice::Determined PyPI target: $TARGET"

  release-build:
    name: Build Release Distributions
    runs-on: ubuntu-latest
    needs:
      - determine-target

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Poetry
        if: ${{ needs.determine-target.outputs.pypi-target == 'test' }}
        uses: abatilo/actions-poetry@v3
        with:
          # TODO - Read this from .poetry-version file
          poetry-version: 1.8.3

      - name: Use temp version if publishing to Test PyPI
        if: ${{ needs.determine-target.outputs.pypi-target == 'test' }}
        run: |
          TMP_VERSION=9999.${{ github.run_id }}.${{ github.run_attempt }}
          echo "Setting temporary version to $TMP_VERSION for Test PyPI publishing"
          poetry version $TMP_VERSION

      - name: Build release distributions
        run: poetry build

      - name: Upload distributions as job artifact
        uses: actions/upload-artifact@v5
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Publish to PyPI (${{ needs.determine-target.outputs.pypi-target }} instance)
    runs-on: ubuntu-latest
    
    needs:
      - determine-target
      - release-build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: publish-to-pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      url: ${{ needs.determine-target.outputs.pypi-target == 'prod' && 'https://pypi.org/project/chipscopy/' || 'https://test.pypi.org/project/chipscopy/' }}

    steps:
      - name: Download release distributions from job artifact
        uses: actions/download-artifact@v5
        with:
          name: release-dists
          path: dist/

      - name: Publish to Test PyPI
        if: ${{ needs.determine-target.outputs.pypi-target == 'test' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: 'https://test.pypi.org/legacy/'
          packages-dir: dist/

      - name: Publish to Prod PyPI
        if: ${{ needs.determine-target.outputs.pypi-target == 'prod' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  # TODO - Once published
  #   - create a job that attempts to install the package from the target PyPI
  #   - creates a GitHub Release for the published version